### ISSUE TITLE
DOI being shown in bibliography entries

### ISSUE THREAD

**Issue by Gor-Ren** [alex-ball/bathbib#1]
Firstly, thanks for this well put-together and documented repo.

I have noticed that my .bib file entries which contain an entry for the 'doi' field are having the DOI printed as a URL in their bibliography entry. For example,

```latex
@article{1995:Phansalkar:REINFORCE_convergence,
author = { V. V. Phansalkar  and  M. A. L. Thathachar },
title = {Local and Global Optimization Algorithms for Generalized Learning Automata},
journal = {Neural Computation},
volume = {7},
number = {5},
pages = {950-973},
year = {1995},
doi = {10.1162/neco.1995.7.5.950},
}
``` 
Results in the entry: 

Phansalkar, V.V. and Thathachar, M.A.L., 1995. Local and global optimiza-
tion algorithms for generalized learning automata. Neural Computation, 7(5),
pp.950–973. **Available from: https://doi.org/10.1162/neco.1995.7.5.950**.

(formatting mine)

The referenced document is from a print journal and shouldn't have a URL specified.

The same behaviour occurs for .bib entries of the @inproceedings type. From reading the Bath Harvard referencing style guidelines, the only document type I can find that should have DOIs are [data sets](http://www.bath.ac.uk/library/infoskills/referencing-plagiarism/harvard-bath-style.html#databases).

Could printing of DOIs be disabled in this referencing style? An alternative workaround is to delete every doi entry in my .bib files, but I'd prefer to preserve the information if possible.

**Comment by alex-ball** [comment]
The motivation for omitting mention of DOIs for most of the referencing guide was to relieve authors of the burden of having to locate and use them, rather than to prevent people from including them if they want to. So the behaviour you see is a Feature, not a Bug.

I realise, however, that this is not what you want to hear, so I will offer you some workarounds to achieve what you want.

# Brute force

Do a search and replace on your .bib file and change your lines like
~~~bibtex
doi = {
~~~
to
~~~bibtex
doid = {
~~~
or another (unique) fieldname of your choosing. The information will then ignored by the styles, but it will still be present in your file, so you will easily be able to reverse this change if migrating to a different style.

# Patching BibTeX

If you are using `bath.bst` or `bathx.bst`, copy the file to your working directory. Open it up and search for the following bit (around line 1380 or 1412 respectively):
~~~bibtex
FUNCTION {format.url}
{ doi empty$
    { url }
    { "https://doi.org/" doi * }
  if$
~~~
Change it to this:
~~~bibtex
FUNCTION {format.url}
{ doi empty$
    { url }
    { type$ "dataset" = { "https://doi.org/" doi * } { "" } if$ }
  if$
~~~

You will have to use `@dataset` instead of `@manual` for datasets for this to function properly.

# The reason why everyone should use biblatex

If you are using the biblatex style, the solution is very easy indeed. After loading the style, include the following lines.

~~~latex
\DeclareFieldFormat{doi}{%
  \ifentrytype{dataset}{%
    \bibsentence\bibstring{urlfrom}\addcolon\space\url{https://doi.org/#1}%
  }{}%
}
~~~

I hope that helps.

**Comment by AnzhiZhang** [comment]
I am posting this to help if anyone need it, it can help to show available from field with `online` field (i.e. only show available from when [Online] field shown). You need to use biblatex.

```latex
% only show available from when is online
\DeclareFieldFormat{url}{%
  \iftoggle{bbx:onlineshown}{%
    \bibsentence\bibstring{urlfrom}\addcolon\space\url{#1}%
  }{}%
}
\DeclareFieldFormat{doi}{%
  \iftoggle{bbx:onlineshown}{%
    \bibsentence\bibstring{urlfrom}\addcolon\space\url{https://doi.org/#1}%
  }{}%
}
```
