### ISSUE TITLE
Suppress `[Online]` tag

### ISSUE THREAD

**Issue by alexreg** [alex-ball/bathbib#11]
I see from the README file that "things will automatically get tagged ‘[Online]’ if you include a URL or DOI". I don't know if this is an essential point of the Bath style, but would it be possible to suppress it? I don't really want articles or books tagged as such (certainly not books), even if they have a DOI or URL, since it can be a little misleading to the reader. Websites, of course, should be tagged as such.

**Comment by alex-ball** [comment]
I'm afraid the [Online] tag *is* an essential point of the [Bath style](https://library.bath.ac.uk/referencing/harvard-bath), as you can see from the book examples. The motivation is that people should be able to refer to the exact same text that you yourself consulted, and the online text may be different to the corresponding print edition; for example, it may include corrections for errors spotted post-publication. With the Bath style, you are expected to omit the URL/DOI if you consulted the printed text, and include a URL/DOI if you consulted an online text, and clearly mark all online texts as such. I know this seems old-fashioned and Internet-averse but there is a logic to it.

If you are using biblatex, you may be able to suppress it by fooling biblatex into thinking the label has already been printed somewhere; in other words, by switching the relevant toggle, perhaps at the end of the title in your .bib file:

```bibtex
title = {Some title or other\toggletrue{bbx:onlineshown}},
```

(you might need `\global` before `\toggletrue`) but this is not tested, recommended or supported.

**Comment by alexreg** [comment]
Thanks for the explanation. And yes, there is a logic to it from a certain point of view, as you say.

Good to know the hack, though given what you've said, I'll probably leave it in now.

**Comment by AnzhiZhang** [comment]
> I'm afraid the [Online] tag _is_ an essential point of the [Bath style](https://library.bath.ac.uk/referencing/harvard-bath), as you can see from the book examples. The motivation is that people should be able to refer to the exact same text that you yourself consulted, and the online text may be different to the corresponding print edition; for example, it may include corrections for errors spotted post-publication. With the Bath style, you are expected to omit the URL/DOI if you consulted the printed text, and include a URL/DOI if you consulted an online text, and clearly mark all online texts as such. I know this seems old-fashioned and Internet-averse but there is a logic to it.
> 
> If you are using biblatex, you may be able to suppress it by fooling biblatex into thinking the label has already been printed somewhere; in other words, by switching the relevant toggle, perhaps at the end of the title in your .bib file:
> 
> ```
> title = {Some title or other\toggletrue{bbx:onlineshown}},
> ```
> 
> (you might need `\global` before `\toggletrue`) but this is not tested, recommended or supported.

Your solution works with `\global`, but it will suppress all bib terms. Is there a way to suppress single [Online] tag without remove doi and url fields (for easy to reaccess because some printted texts are available online as digital copy, but yes I want to keep the url field and I agree with that `reference style does not prevent people from including them if they want to`)?

**Comment by alex-ball** [comment]
You have two options here.

The addendum field is supported in all entry drivers and gets printed just after the URL/DOI fields, so setting

```
addendum = {\global\togglefalse{bbx:onlineshown}},
```

in the bib entry will reset the toggle after you switch it on in `title`. Since it doesn't print any actual text you shouldn't get any problem punctuation.

But since this issue was opened, specifically in v6.0 of the style, I changed how "[Online]" was implemented; the logic now happens in a bibmacro. This means if there is a consistent rule you are following, you can probably implement it directly and avoid hacking entries. For example, if you only want "[Online]" triggered on `online` entries and those where you have provided `urldate` (and not when you only provide `url` or `doi`), then including this after you load the style should do it:

```latex
\renewbibmacro*{isonline}{%
  \ifboolexpr{(
      test {\iffieldundef{urlyear}}
      and
      not test {\ifentrytype{online}}
    ) or
    togl {bbx:onlineshown}
  }{}{%
    \bibstring[\mkbibbrackets]{online}%
    \toggletrue{bbx:onlineshown}}}
```

**Comment by AnzhiZhang** [comment]
You may also need to suppress available from field, please refer to this: https://github.com/alex-ball/bathbib/issues/1#issuecomment-1874281671
