### ISSUE TITLE
Double "[online]" in articles without container-title

### ISSUE THREAD

**Issue by NDR008** [alex-ball/bathbib#17]
Here is an example of a weird looking reference:

```
Mnih, V., Kavukcuoglu, K., Silver, D., Graves, A., Antonoglou, I., Wierstra, D. and Riedmiller, M., 2013. Playing Atari with Deep Reinforcement Learning [Online]. [Online]. Available from: https://arxiv.org/pdf/1312.5602.pdf [Accessed 24 April 2022].
```
Note the double [Online]. Not sure what is causing this. This is as it is saved in Mendeley manager:
![image](https://github.com/alex-ball/bathbib/assets/34957530/fc5b35ab-3dc6-4404-b21c-7a2bdd103b30)

Additionally, I wish I could have [computer program] as per the Bath guide.

**Comment by alex-ball** [comment]
Harvard (Bath) is quite complex and, in order to support all the documented examples, relies on precise encoding. I'm afraid I'm not able to debug your problem from a screenshot from Mendeley. Is there any way you could show me how Mendeley is encoding this in CSL-JSON?

In reference to this and your other email, what you're asking for isn't actually compliant with Harvard (Bath). The `[computer program]` annotation should only be present if the thing you are citing is a computer program, that is, the actual code that runs. In both this example and your other one, you are actually citing a preprint in the arXiv repository, therefore you should be following the format under "Preprint or trial study in a digital repository or registry" in the [Harvard (Bath) specification](https://library.bath.ac.uk/referencing/harvard-bath).

The ideal way to encode these items is as follows:

```json
[
  {
    "id": "silver.etal2017mcs",
    "type": "report",
    "author": [
      { "family": "Silver", "given": "D." },
      { "family": "Hubert", "given": "T." },
      { "family": "Schrittwieser", "given": "J." },
      { "family": "Antonoglou", "given": "I." },
      { "family": "Lai", "given": "M." },
      { "family": "Guez", "given": "A." },
      { "family": "Lanctot", "given": "M." },
      { "family": "Sifre", "given": "L." },
      { "family": "Kumaran", "given": "D." },
      { "family": "Graepel", "given": "T." },
      { "family": "Lillicrap", "given": "T." },
      { "family": "Simonyan", "given": "K." },
      { "family": "Hassabis", "given": "D." }
    ],
    "issued": {
      "date-parts": [ [ 2017 ] ]
    },
    "title": "Mastering Chess and Shogi by Self-Play with a General Reinforcement Learning Algorithm",
    "publisher": "Cornell University",
    "publisher-place": "Ithica, NY",
    "archive": "ArXiv",
    "DOI": "10.48550/arXiv.1712.01815",
    "accessed": {
      "date-parts": [ [ 2023, 1, 25 ] ]
    }
  },
  {
    "id": "mnih.etal2013pad",
    "type": "report",
    "author": [
      { "family": "Mnih", "given": "V." },
      { "family": "Kavukcuoglu", "given": "K." },
      { "family": "Silver", "given": "D." },
      { "family": "Graves", "given": "A." },
      { "family": "Antonoglou", "given": "I." },
      { "family": "Wierstra", "given": "D." },
      { "family": "Riedmiller", "given": "M." }
    ],
    "issued": {
      "date-parts": [ [ 2013 ] ]
    },
    "title": "Playing Atari with Deep Reinforcement Learning",
    "publisher": "Cornell University",
    "publisher-place": "Ithica, NY",
    "archive": "ArXiv",
    "DOI": "10.48550/arXiv.1312.5602",
    "accessed": {
      "date-parts": [ [ 2022, 4, 24 ] ]
    }
  }
]
```

This results in the following output:

> Silver, D., Hubert, T., Schrittwieser, J., Antonoglou, I., Lai, M., Guez, A., Lanctot, M., Sifre, L., Kumaran, D., Graepel, T., Lillicrap, T., Simonyan, K. and Hassabis, D., 2017. *Mastering Chess and Shogi by Self-Play with a General Reinforcement Learning Algorithm.* Ithica, NY: Cornell University. *ArXiv* [Online]. Available from: https://doi.org/10.48550/arXiv.1712.01815 [Accessed 25 January 2023].
>
> Mnih, V., Kavukcuoglu, K., Silver, D., Graves, A., Antonoglou, I., Wierstra, D. and Riedmiller, M., 2013. *Playing Atari with Deep Reinforcement Learning.* Ithica, NY: Cornell University. *ArXiv* [Online]. Available from: https://doi.org/10.48550/arXiv.1312.5602 [Accessed 24 April 2022].

If I can make the style robust against strange input, that would be a bonus, but I need to know what that input is in order to defend against it.

**Comment by alex-ball** [comment]
The issue of the double "[Online]" happens because "[Online]" is supposed to happen after the `container-title` if one is present, otherwise after the `title`. The style was written with the assumption that an article would always have a `container-title`, so in this case,

- we have "[Online]" after `title` because there is no `container-title`;
- because this is an article entry, we have `container-title` (missing), "[Online]", `volume` (missing), `issue` (missing), `page` (missing).

This arises because, as mentioned, Harvard (Bath) treats preprints very much like reports, so it makes sense to encode them like that. The CSL spec, however, says they should be encoded as `article` (as opposed to `article-journal`).

I have made some adjustments so that you can now get the right result using `article` (or `article-journal`) instead, provided

- you supply `archive`, and `publisher` and `publisher-place` if applicable/known;
- you do not use `container-title`.

The difference between `article` and `article-journal` is that `article` expects you have downloaded it from the repository, so it will show the `archive` with "[Online]" next to it even if `container-title` is given. On the other hand, `article-journal` expects you have downloaded it from the journal, so if you provide `container-title`, `archive` is ignored and "[Online]" goes next to `container-title`.

As before, `container-title` steals the italics from `title` if present, but `archive` does not.
