### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by asifm91** [alex-ball/bathbib#4]
I am getting an error during compilation:

> line 512: Package biblatex Error: Option 'mergedate' already defined. ... 'year', 'true' (=year), and 'false'.}}}

I am using MiKTeX 2.9 with TeXstudio in Windows 10. I have installed the package using `mpm` and followed the manual from CTAN to use this citation style. 

Example:

    \documentclass[12pt]{book}
    \usepackage[backend=biber, style=bath,sorting=ynt]{biblatex}
    \assignrefcontextentries[]{*}
    \addbibresource{test.bib}

    \begin{document}
        \nocite{*}
        \newrefcontext[sorting=nyt]
        \printbibliography
    \end{document

FIY, I can use built-in styles or custom ones (ex: biblatex-apa) with biblatex without error.

**Comment by alex-ball** [comment]
Previously the standard authoryear biblatex style only defined `mergedate` as a bibliography option. Version 3.13 introduced `\DeclareBiblatexOption` and, using this, now defines `mergedate` as a type and entry option as well. This conflicts with the type option declared by biblatex-bath.

This will be fixed in the next release.
