### ISSUE TITLE
support for @artwork

### ISSUE THREAD

**Issue by rjschmitt** [alex-ball/bathbib#5]
Thank you very much for this amazing work.
Unfortunately, we miss the @artwork item type, which would be required for e.g. pictures, paintings and other artwork. There is a medium field to describe the kind of the referenced work.

Unfortunately, currently the medium field is ignored and doesn't show up in the bibliography entry.
I hope it's not that hard to implement.

Kind regards

**Comment by alex-ball** [comment]
I presume this relates to the biblatex implementation.

Is there a particular style you are seeking compatibility with? Because while standard biblatex defines `@artwork` as an entry type, it does not define a driver or alias for it (so it falls back to `@misc`). And standard biblatex does not have a `medium` field, which is why it is ignored.

Have you tried adapting the `anon1946peb` example (using the `@image` type) from the manual?

**Comment by rjschmitt** [comment]
Tank you for your fast reply! 
We solved it using the `@image` type with `titleaddon` and that should be ok.
