### ISSUE TITLE
Duplicate date and version info

### ISSUE THREAD

**Issue by moewew** [alex-ball/bathbib#7]
```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=bath, backend=biber]{biblatex}


\begin{filecontents}[force]{\jobname.bib}
@misc{appleby,
  author  = {Humphrey Appleby},
  title   = {On the Importance of the Civil Service},
  date    = {1980-05-06},
  url     = {http://example.com/~sir_humphrey/imp.pdf},
  version = {1},
}
\end{filecontents}
\addbibresource{\jobname.bib}
\addbibresource{biblatex-examples.bib}

\begin{document}
\cite{markey,appleby}
\printbibliography
\end{document}
```
produces

> Appleby, H., 1980. On the importance of the civil service (v.1) [Online]. (V.1). 6 May. Available from: http://example.com/~sir_humphrey/imp.pdf.
>
> Markey, N., 2005. Tame the BeaST: the B to X of BibTeX (v.1.3) [Online]. (V.1.3). 16 October. 16 October. Available from: http://mirror.ctan.org/info/bibtex/tamethebeast/ttb_en.pdf [Accessed 1 October 2006].

It appears that the version field is duplicated for all drivers whose `standard.bbx` version prints the version field and that the date is duplicated for `@online` entries.

**Comment by alex-ball** [comment]
Thank you for testing. I don't see the duplicate version error after the `title` bibmacro was rejigged in commit 4a22038 but I will see if this needs squashing in a more robust fashion.

**Comment by alex-ball** [comment]
The logic currently in place is that the version number is printed as part of the title bibmacro, but if there isn't a title, the version number is printed in the `standard.bbx` position instead. I think I'm happy with that arrangement for now.

The issue was that, prior to commit 4a22038, the title code was (for some punctuation-related reason) wrapped in a `\printtext` that clobbered the `\clearfield`.
