### ISSUE TITLE
Help Request - How to get rid of n.d when date is missing

### ISSUE THREAD

**Issue by FA5I** [alex-ball/bathbib#8]
Hi,

I have some references that are urls to software, and so a date field does not make sense.

I get the following output:

<img width="111" alt="Screenshot 2020-07-27 at 22 00 25" src="https://user-images.githubusercontent.com/56031768/88591651-955dbc80-d054-11ea-8cd3-5a8936e29e00.png">

I read through the docs: [https://anorien.csc.warwick.ac.uk/mirrors/CTAN/macros/latex/contrib/biblatex-contrib/biblatex-bath/biblatex-bath.pdf](https://anorien.csc.warwick.ac.uk/mirrors/CTAN/macros/latex/contrib/biblatex-contrib/biblatex-bath/biblatex-bath.pdf)

However I do not understand how to turn off the date for when it is missing for online sources.

Could someone please assist me in fixing this issue? I am new to latex so may not fully understand the docs!

**Comment by alex-ball** [comment]
University of Bath (Harvard) style is to include a date for software, and for web pages, so this is intentional.

If you are referencing a piece of software, that software was released on a particular date, even if you don't know when that was, so the date field does have meaning. Similarly, if you are referencing the software's official website, the version of the website you are looking at was put online on a particular date, even if it doesn't tell you when that was. The "n.d." means "they did not tell me that date."

Putting that aside, if you insist on removing "n.d", then you have a couple of options.

I recommend you have a read through section 3 of the manual for `biblatex` itself. It is an impressively powerful bit of kit. In there you will find some alternative citation commands you can use, and you may find this formulation useful:

```latex
\parentext{\citetitle{<key>}}
```

biblatex-bath has a trick of its own; you can suppress "n.d." for an individual entry in your bib file like this:

```bibtex
@software{key,
  ...,
  options = {nonodate}
}
```

or for all entries of a given type by putting this in your preamble:

```latex
\ExecuteBibliographyOptions[software]{nonodate}
```

For completeness, you can also turn "n.d." off completely but I really would advise against that.

**Comment by FA5I** [comment]
Thanks @alex-ball !
